### ISSUE TITLE
npm ERR! missing: prompt@0.2.11, required by meteorite@0.7.1

### ISSUE THREAD

**Issue by jimmack1963** [tomrogers3/meteor-winston#5]
Sorry, I'm not clever enough to know how to debug this.  just trying mrt add winston (also got it with winston-loggly first, so I removed and tried this instead).

jim@jim-h9-1130:~/dev/blogtations/dualogs$ mrt --version
Meteorite version 0.7.1
Release 0.7.0.1
jim@jim-h9-1130:~/dev/blogtations/dualogs$ node -v
v0.10.21
jim@jim-h9-1130:~/dev/blogtations/dualogs$ npm -v
1.3.24

**Comment by tomrogers3** [comment]
Hi @jimmack1963, sorry for the delay getting back to you, somehow I missed this at the time. I can't reproduce your issue, this may have been a problem before this library was upgraded to work with Meteor > 0.7. I'm going to close this issue, if you're still having problems please feel free to open this again or create a new issue. Thanks.
